# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('dateCreation', models.DateField(verbose_name="Date de l'evenement")),
                ('jour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jour')),
                ('mois', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mois')),
                ('annee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Année')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Contact')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('annonce', models.TextField(blank=True, null=True, verbose_name='Annonce')),
            ],
            options={
                'verbose_name_plural': 'Annonces',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Evenement')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('dateCreation', models.DateField(verbose_name="Date de l'evenement")),
                ('jour', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jour')),
                ('mois', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mois')),
                ('annee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Année')),
                ('heure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heure')),
                ('hDebut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heure de Début')),
                ('hFin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heure de Fin ')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Contact')),
                ('nbreParticipants', models.IntegerField(blank=True, null=True, verbose_name=' Nbre de Participants')),
                ('bureau', models.IntegerField(blank=True, null=True, verbose_name='Membres du Bureau présents')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Rapport de la réunion')),
                ('odd1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 1')),
                ('odd2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 2')),
                ('odd3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 3')),
                ('odd4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 4')),
                ('odd5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 5')),
                ('odd6', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 6')),
                ('odd7', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 7')),
                ('odd8', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 8')),
                ('odd9', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 9')),
                ('odd10', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordre du Jour 10')),
            ],
            options={
                'verbose_name_plural': 'Evenements',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SujetForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujetforums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sujets_Forum',
            },
        ),
        migrations.CreateModel(
            name='ThemeForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30, unique=True, verbose_name='Titre')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Themes_Forum',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='asseci.Board')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sujetforum',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujetforums', to='asseci.ThemeForum'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='asseci.Topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='sujetforum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='asseci.SujetForum'),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
