# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asseci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactezNous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame')], default='Monsieur', max_length=30, verbose_name='Civilité')),
                ('vousetes', models.CharField(choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], default='Particulier', max_length=30, verbose_name='Vous êtes')),
                ('nom', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresse Email')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Téléphone')),
                ('message', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
